// Notice:  This file shows parameters used in the last simulation for all Links.
//          A subset of these parameters may have been loaded from the (.ADP) file.
//          Use the Additional Parameter file (.ADP) for modifying the parameters.

[VOLUME_SELECTIONS]

	[VOLUME_CALCULATION]
		VolumeID='Volume Trial'
		SelectionFile='Comparison.mus'
	EndSect // VOLUME_CALCULATION
EndSect // VOLUME_SELECTIONS
